import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const base = process.env.JOURNEY_URL ?? 'http://127.0.0.1:5200/';
const output = resolve(process.env.JOURNEY_SCREENSHOTS ?? '/private/tmp/harvard-paper-journey');
await mkdir(output, { recursive: true });
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_CERT_AUTHORITY_INVALID')) errors.push(m.text()); });
  await page.goto(`${base}#/journey/0`, { waitUntil: 'networkidle' });
  await page.locator('.journey-canvas canvas').waitFor();
  await page.waitForTimeout(700);
  assert.match(await page.locator('h1').innerText(), /Harvard/);
  assert.match(await page.locator('.paper-title-citation').innerText(), /fault-tolerant neutral-atom architecture/);
  await page.screenshot({ path: `${output}/00-paper.png`, fullPage: true });
  async function go(i) {
    await page.locator('.journey-chapters button').nth(i).click();
    await page.waitForURL(`**/#/journey/${i}`);
    await page.waitForTimeout(250);
    assert.match(await page.locator('.paper-figure-link').innerText(), /Fig/);
    assert.match(await page.locator('.paper-finding').innerText(), /WHAT THE PAPER/);
  }
  await go(1);
  await page.getByRole('button', { name: '3 Readout', exact: true }).click();
  assert.match(await page.locator('.journey-control-note').innerText(), /shielding beam/);
  await page.screenshot({ path: `${output}/01-zones.png`, fullPage: true });
  await go(2);
  await page.getByRole('button', { name: 'Atom lost', exact: true }).click();
  await page.getByRole('button', { name: '3 Image', exact: true }).click();
  assert.match(await page.locator('.paper-readout-result').innerText(), /Both positions empty: flag loss/);
  assert.match(await page.locator('.paper-camera').getAttribute('aria-label'), /both positions empty/);
  await page.screenshot({ path: `${output}/02-loss-aware-readout.png`, fullPage: true });
  await page.getByRole('button', { name: 'State 1', exact: true }).click();
  assert.match(await page.locator('.paper-readout-result').innerText(), /record 1 and retain/);
  await go(3);
  await page.getByRole('button', { name: 'Smaller code Distance 3' }).click();
  assert.match(await page.locator('.paper-measured-chart').innerText(), /1.33/);
  await page.getByRole('button', { name: 'Larger code Distance 5' }).click();
  assert.match(await page.locator('.paper-measured-chart').innerText(), /0.62/);
  assert.match(await page.locator('.paper-finding').innerText(), /2.14\(13\).*No postselection/);
  await page.screenshot({ path: `${output}/03-below-threshold.png`, fullPage: true });
  await go(4);
  await page.getByRole('button', { name: '3 Gate pulse', exact: true }).click();
  await page.screenshot({ path: `${output}/04-transversal.png`, fullPage: true });
  await page.getByRole('button', { name: 'Lattice surgery Measure a joint boundary' }).click();
  await page.getByRole('button', { name: '3 Measure', exact: true }).click();
  await page.screenshot({ path: `${output}/04-surgery.png`, fullPage: true });
  await go(5);
  await page.getByRole('button', { name: '4 Track result', exact: true }).click();
  assert.match(await page.locator('.journey-control-note').innerText(), /software/);
  await page.screenshot({ path: `${output}/05-universality.png`, fullPage: true });
  await go(6);
  assert.ok(await page.getByRole('button', { name: 'Next layer · swap groups' }).isDisabled());
  await page.getByRole('button', { name: '4 Reset', exact: true }).click();
  await page.screenshot({ path: `${output}/06-reset-reuse.png`, fullPage: true });
  await page.getByRole('button', { name: 'Next layer · swap groups' }).click();
  assert.equal(await page.locator('.paper-cycle-label output').innerText(), '2 / 27');
  await page.getByText('Evidence & important limits').click();
  assert.match(await page.locator('.journey-physics').innerText(), /postselection/);
  assert.match(await page.locator('.journey-physics').innerText(), /do not imply constant logical fidelity/);
  assert.equal(await page.locator('.journey-canvas canvas').count(), 1);

  await page.goto(`${base}#/basics/3`);
  await page.getByLabel('Shift the second wave').waitFor();
  await page.getByLabel('Shift the second wave').fill('180');
  assert.equal(await page.locator('.journey-probability output').first().innerText(), '0%');
  await page.getByRole('link', { name: 'The Harvard paper' }).click();
  await page.locator('.paper-title-citation').waitFor();

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${base}#/journey/0`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(300);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 390);
  await page.screenshot({ path: `${output}/mobile-paper.png`, fullPage: true });
  await go(3);
  await page.getByRole('button', { name: 'Larger code Distance 5' }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 390);
  await page.screenshot({ path: `${output}/mobile-results.png`, fullPage: true });

  await page.goto(`${base}#control`);
  await page.locator('#control').waitFor();
  await page.goto(`${base}#/foundations/qubit`);
  await page.getByRole('heading', { name: 'A qubit, physically', exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log(`PASS: paper-first entrance, Fig. 1–6 coverage, loss-aware readout, reported error bars, logical-gate comparison, universality, reuse, source scopes, optional basics, legacy links, mobile. Screenshots: ${output}`);
} finally { await browser.close(); }
